backend = "glx";
#backend = "xrender";

# global
vsync = true;
#################################

# radius
#################################

corner-radius = 10;

# blur
#################################

blur-method = "dual_kawase";
blur-strength = 4;
blur-background = true;

# opacity
#################################

opacity-rule = [
  "70:class_g = 'kitty'",
  "70:class_g = 'Polybar'"
];
