#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &
pgrep -x dunst >/dev/null || dunst &

# --- env --------------------------
export XDG_CURRENT_DESKTOP='bspwm'
export _JAVA_AWT_WM_NONREPARENTING=1
# ----------------------------------

# ---compositor
picom --config ~/.config/picom/picom.conf &
# --------------

# ---bar
polybar main &
# ------

# ---change language
setxkbmap -layout us,ru -option grp:alt_shift_toggle &
# -------------------

# --- wallpaper -----------------------
feh --bg-fill ~/.config/wallpaper/1.png
# -------------------------------------

# ---monitor
bspc monitor -d 1 2 3 4 5 6
# ----------

# --- theme ------------------------------
bspc config border_width 2
bspc config window_gap 5
bspc config focused_border_color "#9f4559"
bspc config nornal_border_color "#ffffff"
#-----------------------------------------

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
