[greeter]
# GTK themeing
theme-name=RosePineMoon-zk
icon-theme-name=Catppuccin-Mocha
cursor-theme-name=Qogirr-Dark
font-name=JetBrainsMono Nerd Font 10

# Background (picked/updated by greeter-setup-script)
user-background=false
background=/var/cache/lightdm/greeter-wallpaper.webp
background-color=#0d0b1e

# Panel/indicators (hide the default top bar)
indicators=
clock-format=%a %d %b  %H:%M

# Xft
xft-antialias=true
xft-dpi=96
xft-hintstyle=hintslight
xft-rgba=rgb

